# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: breddy.net
email: chris@breddy.net
description: > # this means to ignore newlines until "baseurl:"
    Chris Bredesen's random and infrequent musings, personal and professional.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://breddy.net" # the base hostname & protocol for your site
twitter_username: cbredesen
github_username:  cbredesen

# Build settings
markdown: kramdown
